substitutions:
  node_name: bed_beacon
  platform: ESP32
  board: nodemcu-32s

packages:
  wifi: !include ./common/wifi.yaml
  device_base: !include ./common/device_base.yaml


esp32_ble_beacon:
  type: iBeacon
  uuid: c927bf3b-5b96-d564-c6e0-6dd7df7875f3
